package ss7_abstract_class_and_interface.practice07.class_animal_and_interface_edible_and_fruit.fruit;

import ss7_abstract_class_and_interface.practice07.class_animal_and_interface_edible_and_fruit.edible.Edible;

public abstract class Fruit implements Edible {
}
